name: line_icons
description: Another icon library, based on Awesome Line Icons (by www.icons8.com) and with the help of FlutterIcon.com
version: 0.2.0
author: Germ√°n Alonso<galonsos@gmail.com>
homepage: https://github.com/galonsos

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: LineIcons
      fonts:
        - asset: lib/assets/fonts/LineIcons.ttf
          weight: 400
